### PR TITLE
distribute wayland protocol files

### PR DESCRIPTION
**Pull request by t-8ch**
Fixes `make distcheck`.
(https://github.com/jonls/redshift/pull/663#issuecomment-524414330)

Feel free to squash.

### CODE REVIEW

**Comment by t-8ch** [comment]
This will force users of the distribution tarball to have the wayland-scanner tool available.
We could also package the pre-generated .c and .h files.
Given that even Debian will pull in `wayland-scanner` when installing wayland headers I think it can be kept as is.

**Comment by CameronNemo** [comment]
Wow I just spent a while hunting this down.

> We could also package the pre-generated .c and .h files.

Could that break for different Wayland protocol versions?

**Comment by CameronNemo** [comment]
also I did this:

```
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -130,7 +130,7 @@ endif
 CLEANFILES = *-protocol.c *-client-protocol.h

 %-protocol.c : $(srcdir)/%.xml
-       $(AM_V_GEN)$(MKDIR_P) $(dir $@) && $(WAYLAND_SCANNER) code < $< > $@
+       $(AM_V_GEN)$(MKDIR_P) $(dir $@) && $(WAYLAND_SCANNER) private-code < $< > $@

 %-client-protocol.h : $(srcdir)/%.xml
        $(AM_V_GEN)$(MKDIR_P) $(dir $@) && $(WAYLAND_SCANNER) client-header < $< > $@
```

**Comment by t-8ch** [comment]
> > We could also package the pre-generated .c and .h files.
> 
> Could that break for different Wayland protocol versions?

I have no clue. I would guess not, otherwise you would have to recompile all wayland applications on every version bump.

Packaging the generated files would only have any advantages for people who have `wayland.h` but not `wayland-scanner`. This applies neither to Arch nor Debian

**Comment by minus7** [comment]
Thanks, @t-8ch, merged and squashed it.

@CameronNemo: What does private-code do? Make the generated files not get packaged when using make dist? I didn't see them in the package either way.
You also require wayland-scanner >= 1.15. Any particular reason?

**Comment by t-8ch** [comment]
> What does private-code do?

From `wayland-scanner --help`:

    Use "public-code" only if the marshalling code will be public - aka DSO will export it while other components will be using it.
    Using "private-code" is strongly recommended.

So yeah, `private-code` sounds better.

**Comment by CameronNemo** [comment]
the version bump is related to the public/private split. I thought it was fine to bump because wlroots is often only available on distros with recent wayland versions, and wlroots probably has some wayland version requirement which i have forgotten.

**Comment by minus7** [comment]
Applied both

**Pull request closed without merging**
